# -*- coding: utf-8 -*-
"""ML-HW.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d7gXVx7K23VLZdGPZDumcNUicnZ0XHsh

# **ML**

diabetes

## **Read Data**
"""

# RandomForestClassifier
# sklearn basics
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn import metrics
from sklearn.metrics import ConfusionMatrixDisplay
import pandas as pd

# read data
url = "https://raw.githubusercontent.com/MphBc/Data-test/main/diabetes.csv"
diabetes = pd.read_csv(url)
diabetes.head()

"""## **Split Data**"""

# prepare data
X = diabetes.drop("Outcome", axis = 1)
y = diabetes["Outcome"]

# split data
X_train, X_test, y_train, y_test = train_test_split(
	X, y, test_size = 0.25, random_state = 42 #set.seed()
)

X_train.shape # ( row, column )

"""# **Logistic Regression model**

## **Predict New Data (Scoring)**
"""

# train model
model = LogisticRegression()
model.fit(X_train, y_train)

# test model
p = model.predict(X_test)
print(p)

"""## **Model Evaluation**"""

cnf_matrix = metrics.confusion_matrix(y_test, p)
cnf_matrix

target_names = ['without diabetes', 'with diabetes']
print(classification_report(y_test, p, target_names=target_names))

disp = ConfusionMatrixDisplay(cnf_matrix)
disp = disp.plot()